[tool.isort]
profile = "black"
line_length = 120
skip_glob = "^(event_provider|tests)"

[tool.black]
line-length = 120

[tool.pylint.messages_control]
max-line-length = 120
disable = [
    "missing-module-docstring",
    "missing-class-docstring", 
    "missing-function-docstring",
    "invalid-name"
]